import { ArrowRight, ImagePlus, Layers, SlidersHorizontal, Sparkles, WandSparkles, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import SiteHeader from '../layouts/SiteHeader';
const cards = [
  { icon: <Sparkles size={22}/>, title: 'Nâng cấp ảnh thông minh', text: 'Không gian cho tính năng upscale và khôi phục chi tiết bằng AI.' },
  { icon: <SlidersHorizontal size={22}/>, title: 'Chỉnh màu chuyên nghiệp', text: 'Điều chỉnh ánh sáng, sắc độ và bộ lọc trong một giao diện trực quan.' },
  { icon: <Layers size={22}/>, title: 'Studio sáng tạo', text: 'Chỉnh sửa ảnh nhiều lớp với công cụ lựa chọn và thiết kế.' },
  { icon: <WandSparkles size={22}/>, title: 'Chỉnh sửa bằng ngôn ngữ', text: 'Nhập mô tả tự nhiên để tạo kế hoạch chỉnh sửa khi AI được tích hợp.' },
];
export default function HomePage() {return <div className="site-page"><SiteHeader/><main className="home-content"><section className="home-hero"><div className="hero-copy"><span className="eyebrow"><Zap size={14}/> Không gian sáng tạo thế hệ mới</span><h1>Biến hóa ảnh thật tốc chỉ với <span>chạm AI</span> cho mọi người</h1><p>Khơi nguồn cảm hứng với công cụ chỉnh sửa ảnh tinh tế, dễ dùng và sẵn sàng mở rộng sức mạnh AI.</p><div className="hero-buttons"><Link to="/editor/1" className="button primary big"><ImagePlus size={18}/> Bắt đầu chỉnh sửa <ArrowRight size={17}/></Link><Link to="/projects" className="button outlined big">Khám phá thư viện</Link></div><div className="hero-foot">✦ Bộ giao diện thử nghiệm · Chức năng AI sẽ được kết nối ở các sprint tiếp theo</div></div><div className="hero-art"><div className="hero-glow"></div><div className="showcase-card"><div className="mock-photo"><div className="mock-orbit"></div><div className="mock-sun"></div><div className="mock-hill one"></div><div className="mock-hill two"></div></div><div className="showcase-label"><Sparkles size={16}/> Lumina Creative Studio</div></div><span className="floating-pill float-top">✨ Chỉnh sửa thông minh</span><span className="floating-pill float-bottom">🎨 Giao diện trực quan</span></div></section><section className="home-features"><div className="section-top"><div><span className="section-kicker">KHẢ NĂNG CỦA STUDIO</span><h2>Bộ công cụ AI – Chạm để sáng tạo</h2></div><Link to="/editor/1" className="text-link">Vào Studio <ArrowRight size={16}/></Link></div><div className="feature-grid">{cards.map((card)=><article className="feature-card" key={card.title}><span className="feature-icon">{card.icon}</span><h3>{card.title}</h3><p>{card.text}</p><Link to="/editor/1">Khám phá <ArrowRight size={15}/></Link></article>)}</div></section></main></div>}
